update workflow

diff --git a/.github/workflows/github-workflow.yaml b/.github/workflows/github-workflow.yaml
--- a/.github/workflows/github-workflow.yaml
+++ b/.github/workflows/github-workflow.yaml
@@ -73,10 +73,10 @@ jobs:
           echo "B='b env val'" >> $GITHUB_ENV
 
       - name: Dont fail if command fails
-        run: |
+        run: | # 1st and 2nd lines can be repeated multiple times
           [[ -z "${{ env.BB }}" ]] \
-          && echo "MY_ENV_VAR=${{ env.BB }}" >> $GITHUB_ENV # 1st and 2nd lines can be repeated multiple times \
-          || echo "Feature not available" # returns 0 exit status if previous commands fail, colon can be used insted ':' 
+          && echo "MY_ENV_VAR=${{ env.BB }}" >> $GITHUB_ENV \
+          || echo "Feature not available" # returns 0 exit status if previous commands fail, colon can be used instead ':' 
           
 
       - if: always()
